### ISSUE TITLE
Suggestion: sticky roles

### ISSUE THREAD

**Issue by nenkoszai** [Jo3-L/yagpdb-cc#44]
Would be great feature to control, possibility to exclude which role it shouldnt reassign upon user rejoin and cooldown

**Comment by Jo3-L** [comment]
This is impossible due to a combination of several factors:
1) YAGPDB cannot trigger on role add / remove / update
2) `.Member.Roles` is empty in leave message

TLDR, it is impossible to maintain an accurate list of roles which a given user has unless all the roles in question are given by YAGPDB (or YAGPDB can trigger when the role is given). Because of this, all the current methods of creating a sticky role system are all workarounds (triggering on all messages, for example).

See [this gist](https://gist.github.com/RickeyJLancaster/630e07c80b0deb535f9210da1f9e5fcf) for an implementation using the workaround described.

Closing for now.
