### ISSUE TITLE
Script not working? 

### ISSUE THREAD

**Issue by brybrant** [Jo3-L/yagpdb-cc#72]
Hi! I love this giveaway script btw it has worked perfectly up until now. I just hosted a giveaway on my community Discord server with 207 participants and the bot just announced the winners, saying: "No Participants :("

Please help! Everyone is mad :<

![Screenshot_20200830-183527](https://user-images.githubusercontent.com/31571216/91665880-a89af680-eaf0-11ea-96c2-36484032c01a.png)

**Comment by brybrant** [comment]
I found the reason why it wasn't working, but is there a way to announce the winners on a giveaway that has already ended?

**Comment by thewilloftheshadow** [comment]
I assume you could try to reroll it? Not sure though.
Why wasn't it working for you? It also says no participants on my server

**Comment by brybrant** [comment]
I checked the repo and saw there is a new version of the giveaway script with the ability to reroll a giveaway but I am using V1, so I cannot reroll.

The problem was my fault; the reaction script was not set to run in the giveaway channel so a database of participants was never created. Back in March, I suggested a feature that would circumvent this issue (https://github.com/jonas747/yagpdb/issues/660) because it would avoid the need to use a database by treating the reactions on the message as the database itself. This would also reduce and simplify the giveaway code a lot (currently it is almost 10k characters!)

**Comment by Jo3-L** [comment]
Seems like the issue was resolved, closing.

Re: your second suggestion about `.Message.Reactors` - the Discord API does not provide this information in their message payload, it has to either be 1) cached manually or 2) fetched on demand through the [Get Reactions](https://discord.com/developers/docs/resources/channel#get-reactions) endpoint. As such, while `.Message.Reactors` is not really feasible, it is possible that the endpoint could be exposed to CCs through a function like `getMessageReactions channel_id message_id emoji` returning a slice of User objects on success.
